# Generated by Django 2.1.7 on 2019-11-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('mac', models.CharField(primary_key=True, serialize=False, unique=True, max_length=40)),
                ('nickname', models.CharField(default='Anonymous', max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
