# Generated by Django 2.1.7 on 2019-11-04 14:53

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='mac',
        ),
        migrations.AddField(
            model_name='trainer',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
