# Generated by Django 2.1.7 on 2019-11-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='ip',
        ),
        migrations.AddField(
            model_name='trainer',
            name='mac',
            field=models.CharField(default=0, max_length=40, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
