# Generated by Django 2.1.7 on 2019-11-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0002_auto_20191104_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokemon_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('stamina', models.IntegerField()),
            ],
        ),
    ]
