# Generated by Django 2.1.7 on 2019-11-06 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0003_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'Attack'), (2, 'Defense')])),
                ('result', models.IntegerField(blank=True, choices=[(1, 'Lost'), (2, 'Tie'), (3, 'Win')])),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now=True)),
                ('mode', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Completed')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='pokemon_collection',
            field=models.ManyToManyField(blank=True, to='pokebattle.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokebattle.Trainer'),
        ),
        migrations.AddField(
            model_name='battle',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokebattle.Game'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pokemon_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_pc', to='pokebattle.Pokemon'),
        ),
        migrations.AddField(
            model_name='battle',
            name='pokemon_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_trainer', to='pokebattle.Pokemon'),
        ),
    ]
