# Generated by Django 2.1.7 on 2019-11-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0004_auto_20191106_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_battle',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='pokemon_pc',
            field=models.ManyToManyField(blank=True, related_name='game_pokemon_pc', to='pokebattle.Pokemon'),
        ),
        migrations.AddField(
            model_name='game',
            name='pokemon_trainer',
            field=models.ManyToManyField(blank=True, related_name='game_pokemon_trainer', to='pokebattle.Pokemon'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='num',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Not Defined'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Completed')], default=0),
        ),
    ]
