# Generated by Django 2.1.7 on 2019-11-09 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0005_auto_20191108_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='pokemon_pc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_pc', to='pokebattle.Pokemon'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='pokemon_trainer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_trainer', to='pokebattle.Pokemon'),
        ),
    ]
