# Generated by Django 2.1.7 on 2019-11-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0006_auto_20191109_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='result',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Defined'), (1, 'Lost'), (2, 'Tie'), (3, 'Win')], default=0),
        ),
    ]
