# Generated by Django 2.1.7 on 2019-11-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0008_auto_20191109_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pokemon_pc',
        ),
    ]
