# Generated by Django 3.1.3 on 2020-11-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokebattle', '0010_game_final_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='result',
            field=models.IntegerField(blank=True, choices=[(0, 'Not Defined'), (1, 'Lost'), (2, 'Tie'), (3, 'Won')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='final_result',
            field=models.IntegerField(choices=[(0, 'Not Defined'), (1, 'Lost'), (2, 'Tie'), (3, 'Won')], default=0),
        ),
    ]
